---
# DataPlane CR - registers data plane with control plane
# Name must match cluster-agent certificate CN (default-dataplane)
apiVersion: openchoreo.dev/v1alpha1
kind: DataPlane
metadata:
  name: default-dataplane
  namespace: openchoreo-control-plane
spec:
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-gateway-ca
        namespace: openchoreo-data-plane
        key: ca.crt
  gateway:
    # External port 9080 maps to internal 19080 via k3d loadbalancer
    publicVirtualHost: "*.openchoreoapis.test"
    publicHTTPPort: 9080
    publicHTTPSPort: 9443
    organizationVirtualHost: "*.org.openchoreoapis.test"
    organizationHTTPPort: 9080
    organizationHTTPSPort: 9443
---
# BuildPlane CR - registers build plane with control plane
# Name must match cluster-agent certificate CN (default-buildplane)
apiVersion: openchoreo.dev/v1alpha1
kind: BuildPlane
metadata:
  name: default-buildplane
  namespace: openchoreo-control-plane
spec:
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-gateway-ca
        namespace: openchoreo-build-plane
        key: ca.crt
---
# ObservabilityPlane CR - registers observability plane with control plane
# Name must match cluster-agent certificate CN (default-observabilityplane)
apiVersion: openchoreo.dev/v1alpha1
kind: ObservabilityPlane
metadata:
  name: default-observabilityplane
  namespace: openchoreo-control-plane
spec:
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-gateway-ca
        namespace: openchoreo-observability-plane
        key: ca.crt
  observerURL: http://observer.openchoreo-observability-plane.svc:8080
