---
# ClusterDataPlane CR - registers data plane with control plane
apiVersion: openchoreo.dev/v1alpha1
kind: ClusterDataPlane
metadata:
  name: default
spec:
  planeID: default
  clusterAgent:
    clientCA:
      secretKeyRef:
        name: cluster-agent-tls
        namespace: openchoreo-data-plane
        key: ca.crt
  secretStoreRef:
    name: default
  gateway:
    ingress:
      external:
        http:
          host: openchoreoapis.openchoreovm.test
          listenerName: http
          port: 19080
        name: gateway-default
        namespace: openchoreo-data-plane
---
# ClusterWorkflowPlane CR - registers workflow plane with control plane
apiVersion: openchoreo.dev/v1alpha1
kind: ClusterWorkflowPlane
metadata:
  name: default
spec:
  planeID: default
  clusterAgent:
    clientCA:
      secretKeyRef:
        name: cluster-agent-tls
        namespace: openchoreo-workflow-plane
        key: ca.crt
  secretStoreRef:
    name: default
---
# ClusterObservabilityPlane CR - registers observability plane with control plane
apiVersion: openchoreo.dev/v1alpha1
kind: ClusterObservabilityPlane
metadata:
  name: default
spec:
  planeID: default
  clusterAgent:
    clientCA:
      secretKeyRef:
        name: cluster-agent-tls
        namespace: openchoreo-observability-plane
        key: ca.crt
  observerURL: http://observer.openchoreo-observability-plane.svc.cluster.local:8080
