---
# DataPlane CR - registers data plane with control plane
# Name 'default' matches the single-cluster setup convention
apiVersion: openchoreo.dev/v1alpha1
kind: DataPlane
metadata:
  name: default
  namespace: default
  annotations:
    openchoreo.dev/description: "DataPlane for single-cluster k3d setup"
    openchoreo.dev/display-name: "DataPlane default"
spec:
  planeID: default-dataplane
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-agent-tls
        namespace: openchoreo-data-plane
        key: ca.crt
  secretStoreRef:
    name: default
  gateway:
    organizationVirtualHost: openchoreoapis.internal
    publicVirtualHost: openchoreovm-apis.localhost
  observabilityPlaneRef: default
---
# BuildPlane CR - registers build plane with control plane
# Name 'default' matches the single-cluster setup convention
apiVersion: openchoreo.dev/v1alpha1
kind: BuildPlane
metadata:
  name: default
  namespace: default
  annotations:
    openchoreo.dev/description: "BuildPlane for single-cluster k3d setup"
    openchoreo.dev/display-name: "BuildPlane default"
spec:
  planeID: default-buildplane
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-agent-tls
        namespace: openchoreo-build-plane
        key: ca.crt
  secretStoreRef:
    name: default
  observabilityPlaneRef: default
---
# ObservabilityPlane CR - registers observability plane with control plane
# Name 'default' matches the single-cluster setup convention
apiVersion: openchoreo.dev/v1alpha1
kind: ObservabilityPlane
metadata:
  name: default
  namespace: default
  annotations:
    openchoreo.dev/description: "ObservabilityPlane for single-cluster k3d setup"
    openchoreo.dev/display-name: "ObservabilityPlane default"
spec:
  planeID: default-observabilityplane
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-agent-tls
        namespace: openchoreo-observability-plane
        key: ca.crt
  observerURL: http://observer.openchoreo-observability-plane.svc.cluster.local:8080
