---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: registry
  namespace: openchoreo-build-plane
spec:
  interval: 30m
  chart:
    spec:
      chart: docker-registry
      version: "2.2.3"
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: registry
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: LoadBalancer
      port: 5000
