---
# Pre-install External Secrets Operator CRDs before the data-plane chart
# This is needed because:
# 1. The data-plane chart has post-install hooks that use ClusterSecretStore CRD
# 2. Helm validates ALL hooks before applying any templates
# 3. So it fails trying to validate the hook before CRDs exist
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-crds
  namespace: openchoreo-data-plane
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.19.2"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Only install CRDs, disable all other components
    installCRDs: true
    webhook:
      create: false
    certController:
      create: false
    serviceAccount:
      create: false
    # Disable the operator deployment
    replicaCount: 0
