---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openchoreo-data-plane
  namespace: openchoreo-data-plane
spec:
  interval: 5m
  dependsOn:
    - name: openchoreo-control-plane
      namespace: openchoreo-control-plane
  chart:
    spec:
      chart: openchoreo-data-plane
      version: "0.11.0"
      sourceRef:
        kind: HelmRepository
        name: openchoreo
        namespace: flux-system
      interval: 12h
  install:
    # Retry on CRD timing issues (external-secrets CRDs installed by chart dependencies)
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
  values:
    gateway:
      httpPort: 19080
      httpsPort: 19443
      selfSignedIssuer:
        enabled: false
      envoy:
        mountTmpVolume: true
    # Reuse the existing control plane's cluster gateway controller
    gatewayController:
      enabled: false
    # External Secrets Operator configuration
    external-secrets:
      enabled: true
