---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openchoreo-data-plane
  namespace: openchoreo-data-plane
spec:
  interval: 5m
  dependsOn:
    - name: openchoreo-control-plane
      namespace: openchoreo-control-plane
  chart:
    spec:
      chart: openchoreo-data-plane
      version: "0.12.0"
      sourceRef:
        kind: HelmRepository
        name: openchoreo
        namespace: flux-system
      interval: 12h
  install:
    # Skip OpenAPI validation to avoid CRD chicken-and-egg issue
    # (chart has post-install hooks that use CRDs installed by the chart itself)
    disableOpenAPIValidation: true
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    disableOpenAPIValidation: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: openchoreo-data-plane-values
      valuesKey: values.yaml
