---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openchoreo-control-plane
  namespace: openchoreo-control-plane
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: openchoreo-control-plane
      version: "0.11.0"
      sourceRef:
        kind: HelmRepository
        name: openchoreo
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      # VM uses .test TLD (official uses .localhost)
      baseDomain: openchoreo.test
      port: ":8080"
    # Enable cluster gateway for agent-based data plane communication
    clusterGateway:
      enabled: true
    # Controller Manager cluster gateway configuration
    controllerManager:
      clusterGateway:
        enabled: true
    thunder:
      configuration:
        server:
          publicUrl: "http://thunder.openchoreo.test:8080"
        gateClient:
          hostname: "thunder.openchoreo.test"
          port: 8080
          scheme: "http"
    gateway:
      enabled: true
      envoy:
        enabled: true
        mountTmpVolume: true
