---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openchoreo-control-plane
  namespace: openchoreo-control-plane
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: openchoreo-control-plane
      version: "0.11.0"
      sourceRef:
        kind: HelmRepository
        name: openchoreo
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      baseDomain: openchoreo.dev.local
      port: ":8080"
    gateway:
      httpPort: 80
      httpsPort: 443
      envoy:
        mountTmpVolume: true
    thunder:
      configuration:
        server:
          publicUrl: http://thunder.openchoreo.dev.local:8080
        gateClient:
          hostname: thunder.openchoreo.dev.local
          port: 8080
          scheme: "http"
