---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openchoreo-observability-plane
  namespace: openchoreo-observability-plane
spec:
  interval: 30m
  dependsOn:
    - name: openchoreo-control-plane
      namespace: openchoreo-control-plane
  chart:
    spec:
      chart: openchoreo-observability-plane
      version: "0.11.0"
      sourceRef:
        kind: HelmRepository
        name: openchoreo
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    openSearch:
      enabled: true
    openSearchCluster:
      enabled: false
