---
# DataPlane CR - registers data plane with control plane
apiVersion: openchoreo.dev/v1alpha1
kind: DataPlane
metadata:
  name: default
  namespace: openchoreo-control-plane
spec:
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-gateway-ca
        namespace: openchoreo-data-plane
        key: ca.crt
  gateway:
    publicVirtualHost: "*.openchoreoapis.localhost"
    publicHTTPPort: 19080
    publicHTTPSPort: 19443
    organizationVirtualHost: "*.org.openchoreoapis.localhost"
    organizationHTTPPort: 19080
    organizationHTTPSPort: 19443
---
# BuildPlane CR - registers build plane with control plane
apiVersion: openchoreo.dev/v1alpha1
kind: BuildPlane
metadata:
  name: default
  namespace: openchoreo-control-plane
spec:
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-gateway-ca
        namespace: openchoreo-build-plane
        key: ca.crt
