---
# DataPlane CR - registered with control plane
apiVersion: openchoreo.dev/v1alpha1
kind: DataPlane
metadata:
  name: default
  namespace: openchoreo-control-plane
spec:
  displayName: Default Data Plane
  gatewayEndpoint: http://openchoreoapis.localhost:19080
  kubernetesClusterRef:
    name: in-cluster
    namespace: openchoreo-control-plane
  namespaceRef:
    name: openchoreo-data-plane
---
# BuildPlane CR - registered with control plane
apiVersion: openchoreo.dev/v1alpha1
kind: BuildPlane
metadata:
  name: default
  namespace: openchoreo-control-plane
spec:
  displayName: Default Build Plane
  kubernetesClusterRef:
    name: in-cluster
    namespace: openchoreo-control-plane
  namespaceRef:
    name: openchoreo-build-plane
  registry:
    endpoint: host.k3d.internal:10082
    insecure: true
