---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/helm-repositories.yaml
  - gateway-api
  - cert-manager/namespace.yaml
  - cert-manager/helmrelease.yaml
  - external-secrets/namespace.yaml
  - external-secrets/helmrelease.yaml
